### ISSUE TITLE
Incorporate with Webpack 2 postcss.config.js?

### ISSUE THREAD

**Issue by nathanchase** [sebastian-software/postcss-smart-import#44]
here's my postcss.config.js:

```
const cssnext     = require( 'postcss-cssnext' );
const smartImport = require( 'postcss-smart-import' );

const config = ( webpack ) => ( {
    plugins: [
        smartImport({
            addDependencyTo: webpack
        }),
        cssnext()
    ]
} );

module.exports = config;
```

and my relevant section of webpack.config.js:

```
 resolve: {
...
    modules: ["src", "node_modules"].map(x => path.resolve(x)),
  },
...
{ test: /\.css$/,
        use: [
          'style-loader',
          'css-loader?importLoaders=1',
          'postcss-loader'
        ]
}
```

So in my app.css file, I simply have:

`@import 'normalize.css';`

which throws an error of _Module not found: Error: Can't resolve './normalize.css'_

I can only assume there's some syntax step I'm missing or omitting here...

How does one ensure Webpack 2 understands how to resolve `node_modules` so that PostCSS can import and apply transformations accordingly?

**Comment by nathanchase** [comment]
Solved it on my end. Was just a pathing and node_modules issue.

**Comment by m0ngr31** [comment]
How did you solve this issue? I'm running into the same problem.
